# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc3e8b3d6401230dc84469258974f1ae7571fd29002497da8d2fa0c7ed1638b257dd6b896d33c79cd9ed692924c8dd97a698119f8ca9c2d3aa99f2c08b760464

test:
  secret_key_base: 56ca42453dcae4b08ebb4dab0ad940fa31e814818a4bd59f3cce2ca5b25307ee721f7065ead01e11a20c0eea13877f7b4ec209d620c42c2d0d9873b00caee57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
